### PR TITLE
Rewritten parsers - ~3x performance increase

### PR DESCRIPTION
**Pull request by Salakar**
Re-wrote the javascript parser, averages around 14k ops/s more and ~2-3x faster parsing.

Thoughts?

## Benchmarks
image

Also slightly tweaked the hiredis parser also, ~1-2% change, not really noticeable but every little helps

@luin @BridgeAR tagging you both in.

### CODE REVIEW

**Comment by BridgeAR** [comment]
@Salakar nice! But the optimization for big chunks is gone.

**Comment by Salakar** [comment]
ooo ye, let me look into that, woops. Guess it needs some kind of size check also to vary between chunking or standard?

**Comment by BridgeAR** [comment]
Yepp. If a bulk reply is bigger than the current chunk cache all following chunks until the bulk reply is complete and concat all cached chunks.

**Comment by Salakar** [comment]
Maybe we could persuade either @mscdex or @andrasq to work their performance wizardry / give this a once over look at - v2.0 branch. @ both - this is the main redis resp parser that the 2 main node redis clients for node use, based on:  http://redis.io/topics/protocol

**Comment by mscdex** [comment]
I decided to take a crack at this this evening (writing one from scratch) for fun. So far the results are promising, but I am far from finished yet. There are some more optimizations to be had and type implementations to be completed. Example results as the code stands right now though:

```
multiple chunks in a bulk string
================================
old x 50,943 ops/sec ±0.36% (92 runs sampled)
hiredis x 1,075,063 ops/sec ±0.39% (95 runs sampled)
new x 460,955 ops/sec ±0.82% (94 runs sampled)
mscdex x 1,334,433 ops/sec ±1.63% (93 runs sampled)

Fastest is mscdex

4mb bulk string
===============
old x 329 ops/sec ±0.47% (83 runs sampled)
hiredis x 469 ops/sec ±1.05% (79 runs sampled)
new x 327 ops/sec ±0.48% (65 runs sampled)
mscdex x 1,742 ops/sec ±1.30% (85 runs sampled)

Fastest is mscdex

simple string
=============
old x 2,920,941 ops/sec ±0.90% (93 runs sampled)
hiredis x 2,283,245 ops/sec ±0.44% (92 runs sampled)
new x 4,734,593 ops/sec ±0.37% (93 runs sampled)
mscdex x 5,090,149 ops/sec ±0.42% (91 runs sampled)

Fastest is mscdex

integer
=======
old x 2,688,599 ops/sec ±0.69% (88 runs sampled)
hiredis x 2,185,333 ops/sec ±0.24% (94 runs sampled)
new x 6,014,210 ops/sec ±0.48% (92 runs sampled)
mscdex x 19,786,130 ops/sec ±0.38% (92 runs sampled)

Fastest is mscdex
```

Some initial comments:

  * I suspect that the simple string parsing speed will be about the same as the "new" parser because IIRC most of the time is spent converting Buffers to strings, and there is not much that can be done about that outside of node core.

  * I removed the try-catch from the hiredis js interface since hiredis *could* be modified to not throw also, so removing the try-catch makes things more realistic IMHO when comparing benchmark results. This removal is reflected in the results above.

  * I found a bug with `startBigBuffer`. It is appending `lorem` which causes all of the parsers to fail (due to incorrect string length). Removing the `+ lorem` at the end fixes this.

**Comment by Salakar** [comment]
@mscdex this looks impressive! Be interesting to see how you achieved this

As for hiredis - I think we were deprecating support as in most cases js is way faster than native

Also, any thoughts on @luin 's big array perf on the [v2 proposal pr](https://github.com/NodeRedis/node-redis-parser/pull/3)

**Comment by mscdex** [comment]
@Salakar I actually pulled from the `v.2.0` branch, so the "new" parser is the one from #3 as of this writing.

I have not worked on array, error, or null implementations at all yet.

**Comment by andrasq** [comment]
@Salakar I only got a chance to look at this tonight, wrote an alternate number parser,
then got derailed when I tested with 2^64 - 1.

My approach was to gather the digits numerically into two numeric vars n and m, and return
either the numeric value of n if no overflow, or the string concatenation of n and m otherwise.
@mscdex may have done the same, my results are similar to his (once normalized)

However, when I tested this approach I found that parsing a big number causes the throughput
of all the other test runs to drop by a large amount (close to half), then spent the rest of the time
chasing that glitch.  Never did figure out how to avoid it.

```
old: + integer x 1,882,301 ops/sec ±0.57% (90 runs sampled)
hiredis: + integer x 1,289,520 ops/sec ±0.15% (95 runs sampled)
new: + integer x 3,270,845 ops/sec ±0.80% (90 runs sampled)
andras: + integer x 11,643,973 ops/sec ±0.52% (94 runs sampled)
```

My code, if you want to play with it
```
// gather digits numerically, return string if Number overflow
// 15 digits will not cause overflow, 16 can
function parseSimpleNumbers (parser) {
  var buf = parser.buffer, offset = parser.offset, length = buf.length
  var v, n = 0, m = 1, suffix = '', sign = ''

  if (buf[offset] === 0x2d) { sign = '-'; offset++ }
  var start = offset

  while (offset < length) {
    if (buf[offset] >= 0x30 && buf[offset] <= 0x39) { // '0'..'9'
      if (offset - start < 15) n = (n * 10) + buf[offset++] - 0x30
      else m = (m * 10) + buf[offset++] - 0x30
    }
    else if (buf[offset++] === 0x0a) break; // '\n'
  }
  parser.offset = offset
  if (offset - start > 15 && m !== 1) return sign + n + ('' + m).slice(1)
  return sign ? -n : n
}
```

**Comment by Salakar** [comment]
@andrasq that's an interesting way of doing that, incredibly performant, the benchmarks look identical to what @mscdex so does look like it's the same. Would never of thought of doing it that way, learn something new everyday!

There was two unused vars, removing those ups it by 2mil ops/s here.

Benchmark on my machine:
image

**Comment by andrasq** [comment]
nice!

whoops, the `v` and `suffix` were left over from experiments.
The glitch on my machine is there with both node 5 and 6 (though
node 6 is less affected):
```
node-v5.10.1:
andras: + integer x 11,653,357 ops/sec ±0.43% (87 runs sampled)
andras: + largeInteger x 1,347,323 ops/sec ±0.84% (93 runs sampled)
andras: + integer x 6,224,194 ops/sec ±0.82% (91 runs sampled)

node-v6.0.0:
andras: + integer x 12,459,959 ops/sec ±0.33% (89 runs sampled)
andras: + largeInteger x 1,516,039 ops/sec ±1.75% (90 runs sampled)
andras: + integer x 8,359,377 ops/sec ±0.88% (91 runs sampled)
```

the large integer used was
`var largeIntegerBuffer = new Buffer(':18446744073709551615\r\n');   // (2 ^ 64) - 1`

**Comment by Salakar** [comment]
@andrasq oh ok this happens here for me too:

```text
andras: + integer x 19,008,076 ops/sec ±1.24% (80 runs sampled)
andras: + largeInteger x 2,486,108 ops/sec ±1.02% (81 runs sampled)
andras: + integer x 15,435,560 ops/sec ±1.07% (84 runs sampled)
```

Weirdly only affects integers, if you string then large int then back to string it remains consistent:
```text
andras: + string x 4,615,010 ops/sec ±1.55% (87 runs sampled)
andras: + largeInteger x 2,527,927 ops/sec ±1.03% (87 runs sampled)
andras: + string x 4,612,367 ops/sec ±1.25% (85 runs sampled)
```

**Comment by andrasq** [comment]
it's weird.  Last night I tried `node --trace-gc` and the parse of integerBuffer shows
zero garbage collection before the largeInteger, lots of gc during largeInteger (as expected,
all those strings), but then lots of gc scavenging after largeInteger too even when back to
parsing integerBuffer again.  50-60 gc scavenge runs / second (every 15-20ms) and a couple
of mar-and-sweeps too.

it's possible the benchmark fits in the cpu cache without garbage collection, but once gc kicks in
gc will be a cache buster, with the cache contents bouncing between gc and the script, slowing it. (Which would suggest that the lower value is the more realistic figure to expect in production)
Still not bad though.  Good work that you're doing!

`qtimeit` is a node port of my php tool that I used for years before I started coding node.
I write lots of micro benchmarks, and qtimeit is great for one-liners.

**Comment by Salakar** [comment]
@andrasq could the issue be related to https://github.com/nodejs/node/issues/1671 I wonder, looks GC related

**Comment by andrasq** [comment]
@Salakar I wouldn't think so, that issue is specific to gc-ing Buffers.  Also, the same test run
behaves differently before and after an intervening largeInteger, so it's not gc specifically but
more the state of the system.

**Comment by Salakar** [comment]
@andrasq true, I guess I was thinking that lots of buffers being parsed to `.execute()` was not helping gc, it's been a long day hah. 
 
`qtimeit` is deffo handy though, only saw it today after stalking your github repo's 😆  will be using this more for quick tests. 👍  - also some good tips in your `node-docs` repo

**Comment by andrasq** [comment]
I'm meaning to look at buffer chunking too, had not had time yet.  Until then, a while back I wrote a
package `qbuffers` to coalesce and re-split buffers for a beanstalkd driver, might find ideas in there.
(qbuffers will coalesce buffers, can re-split on user-defined delimiters, and can return either strings
or buffer slices.)

**Comment by Salakar** [comment]
Closing in favour of #3 and #4

**Comment by andrasq** [comment]
for the 4mb bulk string, I don't see an obvious path to a 5x speedup.  On my system
(an older AMD box, much lower memory bandwidth than newer Intel systems) 1000 runs
of the 4mb bulk string test take about 12 seconds, 7.5 sec for the buffer concat and 4.5
for the utf8 conversion.  For buffer returns the utf8 conversion is avoided but the concat
is needed.  For string responses the utf8 conversion is necessary.  If the api requires
that the data be combined and returned in a contiguous block, the merge/convert
overheads are unavoidable.
```
Baseline, 1000 calls:
11.68 - total
 7.26 - buffer concat (coalesce)
 4.40 - utf8 conversion of concated buffer (toString)
 0.02 - other
```

For string responses, concatenating strings appears twice as fast as buffers,
suggesting a possibility for a 45% gain.  Streams might help with this, to ease
the handling of char fragments split by buffer boundaries.
```
Pre-converted sub-strings, 1000 calls:
 8.08 - utf8-convert each chunk separately, then concat the results
 4.12 - utf8 conversion of the 64 64k chunks (toString)
 3.93 - the concat of the 64 64k sub-strings (coalesce)
```

For buffers, copying the chunks into a preallocated merge buffer hints that
a similar gain as the above may be possible without pre-converting,
just by avoiding the Buffer.concat.
```
Copy chunks into merge buffer, 100 calls:
 0.825 - total
 0.371 - buffer.copy (coalesce)
 0.409 - utf8 convert (toString)
 0.038 - other
```

**Comment by Salakar** [comment]
@andrasq thanks for pointing us in the right direction, we've got some decent increases in perf now on the 4mb bulk strings and the other benchmarks, results here if you're interested: https://github.com/NodeRedis/node-redis-parser/pull/3

**Pull request closed without merging**
